### ISSUE TITLE
Completion stops if error occurs while loading tags

### ISSUE THREAD

**Issue by danrharms** [syohex/emacs-ac-etags#4]
If one of the elements of `tags-table-list` is missing (not yet generated or deleted from disk, for example), emacs-ac-etags stops executing, as you would expect, but the error from `(tags-completion-table)` stops completion entirely.  That is, even if there are other valid completion sources added to `ac-sources`, the user does not have a chance to auto-complete using those sources, because of the error.

**Comment by syohex** [comment]
Merged #5. Please check latest version.
